# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CineFlex' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CineFlex
  pod 'Alamofire', '~> 4.7.0'
  pod 'AlamofireImage', '~> 3.4.0'
  
  target 'CineFlexUITests' do
    # Pods for testing
    pod 'Nimble'
    pod 'Quick'
    pod 'Nimble-Snapshots'
  end
  
end
